blogTitle = "RT狂の思考ログ"
authorName = "wkwkrnht"
authorDetail = "モバイル界隈のRT狂"
linkPrefix = ""
googleAnalyticsId = ""
syntaxTheme = "atom-one-dark"
twitterId = "wkwkrnht"
facebookId = ""
githubId = "wkwkrnht"