blogTitle = "undefined"
authorName = "kentaro-m"
authorDetail = "I'm a application engineer."
linkPrefix = ""
googleAnalyticsId = ""
syntaxTheme = "atom-one-dark"
twitterId = ""
facebookId = ""
githubId = "kentaro-m"
